/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryCourseRouteImport } from './routes/history.$course'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCourseRoute = HistoryCourseRouteImport.update({
  id: '/history/$course',
  path: '/history/$course',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/lookup': typeof LookupRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/history/$course': typeof HistoryCourseRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/lookup': typeof LookupRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/history/$course': typeof HistoryCourseRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/lookup': typeof LookupRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/history/$course': typeof HistoryCourseRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/help'
    | '/lookup'
    | '/reports'
    | '/results'
    | '/settings'
    | '/history/$course'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/help'
    | '/lookup'
    | '/reports'
    | '/results'
    | '/settings'
    | '/history/$course'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/help'
    | '/lookup'
    | '/reports'
    | '/results'
    | '/settings'
    | '/history/$course'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  LookupRoute: typeof LookupRoute
  ReportsRoute: typeof ReportsRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  HistoryCourseRoute: typeof HistoryCourseRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$course': {
      id: '/history/$course'
      path: '/history/$course'
      fullPath: '/history/$course'
      preLoaderRoute: typeof HistoryCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  LookupRoute: LookupRoute,
  ReportsRoute: ReportsRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  HistoryCourseRoute: HistoryCourseRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
